server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    datasource:
        url: jdbc:mysql://{url}/gware?serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: {username}
        password: {password}
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
    configuration:
        jdbc-type-for-null: null
        map-underscore-to-camel: true

    mapper-locations: classpath:/mapper/**.xml
    type-aliases-package: com.dev.gware